-- Utilities based on a smarter syntax parser
return {
  'nvim-treesitter/nvim-treesitter',
  version = '*',
  main = 'nvim-treesitter.configs',
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'css',
      'diff',
      'dockerfile',
      'gitcommit',
      'gitignore',
      'haskell',
      'html',
      'javascript',
      'jq',
      'json',
      'json5',
      'just',
      'kdl',
      'lua',
      'make',
      'markdown',
      'markdown_inline',
      'menhir',
      'nix',
      'ocaml',
      'ocaml_interface',
      'ocamllex',
      'perl',
      'properties',
      'python',
      'regex',
      'rst',
      'rust',
      'sql',
      'ssh_config',
      'toml',
      'tsx',
      'typescript',
      'yaml',
    },
    ignore_install = {
      'latex',
    },
    auto_install = true,
    highlight = {
      enable = true,
    },
    indent = { enable = true },
  }
}
